version: 0.2

env:
  variables:
    ImageName: assignment3-repo

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

      - aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 539247461447.dkr.ecr.ca-central-1.amazonaws.com
  build:
    commands: 
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $ImageName -f Dockerfile .
      - docker tag $ImageName:latest 539247461447.dkr.ecr.ca-central-1.amazonaws.com/$ImageName:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 539247461447.dkr.ecr.ca-central-1.amazonaws.com/$ImageName:latest
